Workaround assembler issues in the Microsoft toolchain
Microsoft/mu_silicon_arm_tiano pull request #5
Opened 2019-05-14 23:10 UTC by chris-oo

The assembler still assembles TLBI instructions incorrectly so workaround the issue using the SYS instruction alias.

2019-05-15 05:08 UTC, corthon requested changes

2019-05-15 05:08 UTC, corthon commented on ArmPkg/Library/ArmLib/AArch64/ArmLibSupport.masm
> +   // TODO-cho: Use the alternate encoding of tlbi due to the assembler not
TODO-cho?

2019-05-15 05:08 UTC, corthon commented on ArmPkg/Library/ArmLib/AArch64/ArmLibSupport.masm
> +   // TODO-cho-19475344: Promote the tlbi to vmalle1is due to the assembler not
All changes need MU_CHANGE comments.

2019-05-15 05:08 UTC, corthon commented on ArmPkg/Library/ArmSmcPsciResetSystemLib/AArch64/Reset.asm
> +  ; TODO-cho: The Microsoft assembler does not support the movl pseudo-instruction.
Does this need an associated TCBZ bug?

2019-05-16 18:23 UTC, chris-oo commented on ArmPkg/Library/ArmSmcPsciResetSystemLib/AArch64/Reset.asm
> +  ; TODO-cho: The Microsoft assembler does not support the movl pseudo-instruction.
Yeah we should get something filed.

2019-05-16 18:23 UTC, chris-oo commented on ArmPkg/Library/ArmLib/AArch64/ArmLibSupport.masm
> +   // TODO-cho: Use the alternate encoding of tlbi due to the assembler not
Fixed in latest

2019-05-16 18:24 UTC, chris-oo commented on ArmPkg/Library/ArmLib/AArch64/ArmLibSupport.masm
> +   // TODO-cho-19475344: Promote the tlbi to vmalle1is due to the assembler not
Fixed in latest as well

2019-05-16 20:04 UTC, corthon approved these changes

2019-05-16 20:28 UTC, merged